name: Deploy Pelayanan Desa

on:
  push:
    branches: [ main ]

jobs:
  # --- JOB 1: DEPLOY BACKEND (PAKAI JALUR PROXY OTOMATIS) ---
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend via Proxy
        uses: appleboy/ssh-action@master
        with:
          # Target utama sekarang langsung IP Private Backend
          host: ${{ secrets.BACKEND_IP }} 
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Jembatannya (Proxy/Bastion) adalah Frontend
          proxy_host: ${{ secrets.FRONTEND_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script_stop: true
          # Script di bawah ini sekarang otomatis dijalankan di EC2 BACKEND
          script: |
            cd ~/pelayanan-desa
            git pull origin main
            cd backend
            
            # Injeksi .env asli
            echo "${{ secrets.BACKEND_ENV }}" > .env
            
            # Rebuild & Run Docker
            sudo docker build -t backend-desa .
            sudo docker stop backend-app || true
            sudo docker rm backend-app || true
            sudo docker run -d -p 5000:5000 --name backend-app --restart always backend-desa
            
  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            cd ~/pelayanan-desa
            git pull origin main
            cd frontend
            
            # INJEKSI .ENV & NGINX.CONF ASLI (Menimpa Dummy)
            echo "${{ secrets.FRONTEND_ENV }}" > .env
            echo '${{ secrets.FRONTEND_NGINX }}' > nginx.conf
            
            sudo docker build -t frontend-desa .
            sudo docker stop frontend-app || true
            sudo docker rm frontend-app || true
            sudo docker run -d -p 80:80 --name frontend-app --restart always frontend-desa